from lib import FontMetadata

fonts = [
    FontMetadata(
        owner="microsoft",
        repo="cascadia-code",
        tag="",
        filename="",
        filename_start_with="",
        download_url="",
    ),
    FontMetadata(
        owner="dtinth",
        repo="comic-mono-font",
        tag="",
        filename="ComicMono.ttf",
        filename_start_with="",
        download_url="https://dtinth.github.io/comic-mono-font/ComicMono.ttf",
    ),
    FontMetadata(
        owner="tonsky",
        repo="FiraCode",
        tag="",
        filename="",
        filename_start_with="",
        download_url="",
    ),
    FontMetadata(
        owner="vercel",
        repo="geist-font",
        tag="",
        filename="",
        filename_start_with="GeistMono",
        download_url="",
    ),
    FontMetadata(
        owner="IBM",
        repo="plex",
        tag="@ibm/plex-mono@1.0.0",
        filename="ibm-plex-mono.zip",
        filename_start_with="",
        download_url="",
    ),
    FontMetadata(
        owner="source-foundry",
        repo="Hack",
        tag="",
        filename="Hack-v3.003-ttf.zip",
        filename_start_with="",
        download_url="",
    ),
    # FontMetadata(
    #     owner="be5invis",
    #     repo="Iosevka",
    #     tag="",
    #     filename="",
    #     filename_start_with="PkgTTF-IosevkaFixed-",
    #     download_url="",
    # ),
    FontMetadata(
        owner="JetBrains",
        repo="JetBrainsMono",
        tag="",
        filename="",
        filename_start_with="",
        download_url="",
    ),
    FontMetadata(
        owner="googlefonts",
        repo="RobotoMono",
        tag="",
        filename="RobotoMono-Regular.ttf",
        filename_start_with="",
        download_url="https://github.com/googlefonts/RobotoMono/raw/main/fonts/ttf/RobotoMono-Regular.ttf",
    ),
    FontMetadata(
        owner="googlefonts",
        repo="dm-mono",
        tag="",
        filename="DMMono-Regular.ttf",
        filename_start_with="",
        download_url="https://github.com/googlefonts/dm-mono/raw/refs/heads/main/exports/DMMono-Regular.ttf",
    ),
    FontMetadata(
        owner="eigilnikolajsen",
        repo="commit-mono",
        tag="",
        filename="",
        filename_start_with="",
        download_url="",
    ),
]
