import os

from lib import (
    TEMP_DIR_FONTS,
    TtfOtf,
)

ttf_otf_files = [
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "cascadia-code",
            "ttf",
            "static",
            "CascadiaCode-Light.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss19",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "cascadia-code",
            "ttf",
            "static",
            "CascadiaCode-LightItalic.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss01,ss19",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "cascadia-code",
            "ttf",
            "static",
            "CascadiaCode-SemiLight.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss19",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "cascadia-code",
            "ttf",
            "static",
            "CascadiaCode-SemiLightItalic.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss01,ss19",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "cascadia-code",
            "ttf",
            "static",
            "CascadiaCode-Regular.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss19",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "cascadia-code",
            "ttf",
            "static",
            "CascadiaCode-Italic.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss01,ss19",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "FiraCode",
            "ttf",
            "FiraCode-Regular.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="cv01,cv02,cv10,ss01,ss05,cv16",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "geist-font",
            "GeistMono*",
            "ttf",
            "GeistMono-UltraLight.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss01,ss06,ss08",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "geist-font",
            "GeistMono*",
            "ttf",
            "GeistMono-Light.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss01,ss06,ss08",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "geist-font",
            "GeistMono*",
            "ttf",
            "GeistMono-Regular.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss01,ss06,ss08",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "geist-font",
            "GeistMono*",
            "ttf",
            "GeistMono-Medium.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss01,ss06,ss08",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "geist-font",
            "GeistMono*",
            "ttf",
            "GeistMono-SemiBold.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss01,ss06,ss08",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "Hack",
            "ttf",
            "Hack-Regular.ttf",
        ),
        enable_stylistic_sets=False,
        stylistic_sets="",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "Hack",
            "ttf",
            "Hack-Italic.ttf",
        ),
        enable_stylistic_sets=False,
        stylistic_sets="",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "plex",
            "ibm-plex-mono",
            "fonts",
            "complete",
            "ttf",
            "IBMPlexMono-Regular.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="zero,salt",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "plex",
            "ibm-plex-mono",
            "fonts",
            "complete",
            "ttf",
            "IBMPlexMono-Italic.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="zero,ss06",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "Iosevka",
            "IosevkaFixed-Regular.ttf",
        ),
        enable_stylistic_sets=False,
        stylistic_sets="",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "Iosevka",
            "IosevkaFixed-Italic.ttf",
        ),
        enable_stylistic_sets=False,
        stylistic_sets="",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "JetBrainsMono",
            "fonts",
            "ttf",
            "JetBrainsMono-Regular.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="cv01,cv02,cv15,cv20,zero",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "JetBrainsMono",
            "fonts",
            "ttf",
            "JetBrainsMono-Italic.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="cv01,cv02,cv15,cv20,zero",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "JetBrainsMono",
            "fonts",
            "ttf",
            "JetBrainsMono-Light.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="cv01,cv02,cv15,cv20,zero",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "JetBrainsMono",
            "fonts",
            "ttf",
            "JetBrainsMono-LightItalic.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="cv01,cv02,cv15,cv20,zero",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "commit-mono",
            "CommitMono-*",
            "ttfautohint",
            "CommitMono-400-Regular.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="cv01,cv02,cv10",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "commit-mono",
            "CommitMono-*",
            "ttfautohint",
            "CommitMono-400-Italic.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="cv01,cv02,cv10",
    ),
    TtfOtf(
        path=os.path.join(
            TEMP_DIR_FONTS,
            "DMMono-Regular.ttf",
        ),
        enable_stylistic_sets=True,
        stylistic_sets="ss02,ss03,ss05",
    ),
]
